name: Generate Pdf and Release

# refer to https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml 

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

env:
  CACHE_FROM_DIR: /tmp/.buildx-cache
  DOCKER_BUILDKIT: 1


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        # Use the action from the master, as we've seen some inconsistencies with @v1
        # Issue: https://github.com/docker/build-push-action/issues/286
        uses: docker/setup-buildx-action@master
        # Only worked for us with this option on 🤷‍♂️
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_FROM_DIR }}
          # Key is named differently to avoid collision
          key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-multi-buildx
      - name: Init directory
        run: mkdir -p output
      # Build and push Docker image with Buildx (don't push on PR)
      - name: Build And Gen Pdf
        working-directory: ./
        run: ./gen_pdf.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./output/book.pdf
          draft: true
          prerelease: true